framework: mocha
postMerge:
  pattern:
    - "test/socket.io.ts"
preMerge:
  pattern:
    - "test/socket.io.ts"
preRun:
  command:
    - npm ci
    - npm run compile
postRun:
  command:
    - node --version
parallelism: 2
splitMode: file
version: 1.0
